---
abstract: 'Request logging from within Catalyst'
author:
  - 'Andrew Rodland <andrew@hbslabs.com>'
  - 'Murray <sysmon@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092071'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-AccessLog
requires:
  Catalyst::Runtime: 5.8004
  DateTime: 0
  Moose: 0
  Scalar::Util: 0
  namespace::autoclean: 0
version: 0.02
