---
abstract: 'Request logging from within Catalyst'
author:
  - 'Andrew Rodland <andrew@hbslabs.com>'
  - 'Murray <sysmon@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-AccessLog
requires:
  Catalyst::Runtime: 5.80008
  DateTime: 0
  Moose: 0
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/arodland/Catalyst-Plugin-AccessLog.git
version: 1.04
